--THE MOST 2 TRAVELLERS COUNTRIES
SELECT TOP 2 COUNTRY_NAME, COUNT(PASSENGER_SK) AS COUNT_OF_PASSENGERS FROM SUB_DIM_CONTINENT C JOIN DIM_AIRPORT A
ON C.AIRPORT_COUNTRY_CODE = A.AIRPORT_COUNTRY_CODE JOIN FACT_AIRLINE F
ON F.AIRPORT_SK = A.AIRPORT_SK
WHERE FLIGHT_STATUS != 'Cancelled'
GROUP BY COUNTRY_NAME
ORDER BY COUNT_OF_PASSENGERS DESC

-- WHICH IS THE MOST MONTH HAS FLIGHTS
SELECT P.MONTH FROM DIM_DATE P JOIN FACT_AIRLINE F
ON P.DATE_SK  = F.DATE_SK JOIN DIM_AIRPORT A ON A.AIRPORT_SK = F.AIRPORT_SK
WHERE FLIGHT_STATUS != 'Cancelled'
GROUP BY P.MONTH
ORDER BY COUNT(A.DEPARTURE_DATE) DESC

-- HOW MANY PASSENGERS TRAVEL EVERY MONTH
SELECT P.MONTH , COUNT(F.PASSENGER_SK) AS COUNT_OF_PASSENGER FROM DIM_DATE P JOIN FACT_AIRLINE F
ON P.DATE_SK  = F.DATE_SK JOIN DIM_AIRPORT A ON A.AIRPORT_SK = F.AIRPORT_SK
WHERE FLIGHT_STATUS != 'Cancelled'
GROUP BY P.MONTH
ORDER BY COUNT_OF_PASSENGER DESC

-- COUNT OF CACELLED TRIPS FOR EACH COUNTRY 
SELECT COUNT(A.FLIGHT_STATUS) AS COUNT_OF_CANCELLED_FLIGHTS , C.COUNTRY_NAME FROM DIM_AIRPORT A JOIN SUB_DIM_CONTINENT C
ON C.AIRPORT_COUNTRY_CODE = A.AIRPORT_COUNTRY_CODE
WHERE A.FLIGHT_STATUS = 'Cancelled'
GROUP BY C.COUNTRY_NAME
ORDER BY COUNT_OF_CANCELLED_FLIGHTS DESC

-- COUNT OF CACELLED TRIPS FOR EACH
SELECT COUNT(A.FLIGHT_STATUS) AS COUNT_OF_CANCELLED_FLIGHTS , D.MONTH FROM DIM_AIRPORT A JOIN FACT_AIRLINE F
ON F.airport_sk = A.AIRPORT_SK JOIN DIM_DATE D
ON D.DATE_SK = F.DATE_SK
WHERE A.FLIGHT_STATUS = 'Cancelled'
GROUP BY D.MONTH
ORDER BY COUNT_OF_CANCELLED_FLIGHTS DESC

-- TOP 1 VISITED CONTINENT 
SELECT TOP 1 CONTINENTS, COUNT(PASSENGER_SK) AS COUNT_OF_PASSENGERS FROM SUB_DIM_CONTINENT C JOIN DIM_AIRPORT A
ON C.AIRPORT_COUNTRY_CODE = A.AIRPORT_COUNTRY_CODE JOIN FACT_AIRLINE F
ON F.AIRPORT_SK = A.AIRPORT_SK
WHERE FLIGHT_STATUS != 'Cancelled'
GROUP BY CONTINENTS
ORDER BY COUNT_OF_PASSENGERS DESC

--TOP TRAVELLER
SELECT TOP 1 P.PASSENGER_SK , FIRST_NAME ||' '|| LAST_NAME AS PASSENGER_NAME, COUNT(FLIGHT_STATUS) 
FROM DIM_PASSENGER P JOIN FACT_AIRLINE F ON P.PASSENGER_SK = F.PASSENGER_SK JOIN 
DIM_AIRPORT A ON A.AIRPORT_SK = F.AIRPORT_SK
WHERE FLIGHT_STATUS != 'Cancelled'
GROUP BY P.FIRST_NAME, P.LAST_NAME , P.PASSENGER_SK
ORDER BY COUNT(F.AIRPORT_SK) DESC

-- TOP CANCELLER
SELECT TOP 1 P.PASSENGER_SK , FIRST_NAME ||' '|| LAST_NAME AS PASSENGER_NAME , COUNT(FLIGHT_STATUS)
FROM DIM_PASSENGER P JOIN FACT_AIRLINE F ON P.PASSENGER_SK = F.PASSENGER_SK JOIN 
DIM_AIRPORT A ON A.AIRPORT_SK = F.AIRPORT_SK
WHERE FLIGHT_STATUS = 'Cancelled'
GROUP BY P.FIRST_NAME, P.LAST_NAME , P.PASSENGER_SK
ORDER BY COUNT(F.AIRPORT_SK) DESC

-- NUMBER OF FEMALES 
SELECT COUNT(GENDER) AS NUMBER_OF_FEMALES FROM DIM_PASSENGER P
WHERE GENDER = 'Female';

--NUMBER OF MALES
SELECT COUNT(GENDER) NUMBER_OF_MALES FROM DIM_PASSENGER P
WHERE GENDER = 'Male';

--TOP PILOT
SELECT TOP 1 PILOT_NAME, COUNT(FLIGHT_STATUS) AS COUNT_OF_FLIGHTS FROM DIM_AIRPORT A
WHERE FLIGHT_STATUS = 'On Time'
GROUP BY PILOT_NAME
ORDER BY COUNT_OF_FLIGHTS

-- MOST CROWDED AIRPORT IN 6/28/2022
SELECT TOP 1 AIRPORT_NAME , COUNT(FLIGHT_STATUS) AS COUNT_OF_FLIGHTS FROM DIM_AIRPORT
WHERE FLIGHT_STATUS != 'Cancelled' and departure_date = '6/28/2022'
GROUP BY AIRPORT_NAME
ORDER BY COUNT_OF_FLIGHTS DESC

-- TOP 2 VISITED COUNTRIES
SELECT TOP 2 COUNTRY_NAME ,COUNT(A.ARRIVAL_AIRPORT) AS NUMBER_OF_VISITED_CONTRIES  FROM SUB_DIM_CONTINENT C JOIN DIM_AIRPORT A
ON C.AIRPORT_COUNTRY_CODE = A.AIRPORT_COUNTRY_CODE
GROUP BY COUNTRY_NAME
ORDER BY NUMBER_OF_VISITED_CONTRIES DESC

--PILOT NAMES FOR JANUARY FLIGHTS
SELECT A.PILOT_NAME , FULL_DATE FROM DIM_AIRPORT A JOIN FACT_AIRLINE F ON F.AIRPORT_SK = A.AIRPORT_SK
JOIN DIM_DATE D ON F.DATE_SK = D.DATE_SK 
WHERE D.MONTH = 1
ORDER BY D.DAY
-- count of travellers
SELECT count(PASSENGER_SK) FROM FACT_AIRLINE F JOIN DIM_AIRPORT A
ON F.AIRPORT_SK = A.AIRPORT_SK
WHERE FLIGHT_STATUS != 'Cancelled'
