SELECT * FROM ALL_DATA

-- CHECK NULLS 
SELECT 
    COUNT_IF(PASSENGER_ID IS NULL) AS NULLS_OF_PASSENGER_ID,
    COUNT_IF(FIRST_NAME IS NULL) AS NULLS_OF_FIRST_NAME ,
    COUNT_IF(LAST_NAME IS NULL) AS NULLS_OF_LAST_NAME ,
    COUNT_IF(GENDER IS NULL) AS NULLS_OF_GENDER ,
    COUNT_IF(AGE IS NULL) AS NULLS_OF_AGE ,
    COUNT_IF(NATIONALITY IS NULL) AS NULLS_OF_NATIONALITY ,
    COUNT_IF(AIRPORT_NAME IS NULL) AS NULLS_OF_AIRPORT_NAME ,
    COUNT_IF(AIRPORT_COUNTRY_CODE IS NULL) AS NULLS_OF_AIRPORT_COUNTRY_CODE ,
    COUNT_IF(COUNTRY_NAME IS NULL) AS NULLS_OF_COUNTRY_NAME ,
    COUNT_IF(AIRPORT_CONTINENT IS NULL) AS NULLS_OF_AIRPORT_CINTINENT ,
    COUNT_IF(CONTINENTS IS NULL) AS NULLS_OF_CONTINENTS ,
    COUNT_IF(DEPARTURE_DATE IS NULL) AS NULLS_OF_DEPARTURE_DATE ,
    COUNT_IF(ARRIVAL_AIRPORT IS NULL) AS NULLS_OF_ARRIVAL_AIRPORT ,
    COUNT_IF(PILOT_NAME IS NULL) AS NULLS_OF_PILOT_NAME ,
    COUNT_IF(FLIGHT_STATUS IS NULL) AS NULLS_OF_FLIGHT_STATUS ,
FROM ALL_DATA
-- 0 NULLS 

-- CHECK DUPLICATES

SELECT *,COUNT(*) FROM ALL_DATA
GROUP BY 
PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE,NATIONALITY , AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME, AIRPORT_CONTINENT,CONTINENTS,DEPARTURE_DATE, ARRIVAL_AIRPORT,PILOT_NAME, FLIGHT_STATUS
HAVING COUNT(*)>1
-- 0 DUPLICATES

-- ADDING SURRGET KEYS
ALTER TABLE ALL_DATA
ADD COLUMN DATE_SK INT,
AIRPORT_SK INT,
PASSENGER_SK INT

ALTER TABLE ALL_DATA
ADD COLUMN AIRLINE_SK INT

-- ADDING VALUES TO SURREGETS 
UPDATE  ALL_DATA
SET 
DATE_SK = SEQ4() + 1,
AIRPORT_SK = SEQ4() + 1,
PASSENGER_SK = SEQ4() +1

UPDATE  ALL_DATA
SET 
AIRLINE_SK = SEQ4() + 1

-- ADDING  DATE DATE COLUMNS
ALTER TABLE ALL_DATA
ADD COLUMN FULL_DATE DATE ,
YEAR INT,
MONTH INT ,
DAY INT 

UPDATE all_data a
SET full_date = t.full_date
FROM (
    SELECT 
        passenger_SK,
        CASE 
            WHEN DATEADD(day, ROW_NUMBER() OVER (ORDER BY passenger_SK) - 1, '2022-01-01') > '2022-12-31' 
            THEN '2022-12-31'
            ELSE DATEADD(day, ROW_NUMBER() OVER (ORDER BY passenger_SK) - 1, '2022-01-01')
        END AS full_date
    FROM all_data
) t
WHERE a.passenger_SK = t.passenger_SK;


SELECT FULL_DATE FROM ALL_DATA

UPDATE all_data
SET YEAR = EXTRACT(YEAR FROM FULL_DATE),
    MONTH = EXTRACT(MONTH FROM FULL_DATE),
    DAY = EXTRACT(DAY FROM FULL_DATE)

SELECT YEAR FROM ALL_DATA;
SELECT DAY FROM ALL_DATA;
SELECT MONTH FROM ALL_DATA;

-- CREATION OF DIMENSIONS AND FACTS 

CREATE TABLE DIM_PASSENGER AS
SELECT PASSENGER_SK , PASSENGER_ID, FIRST_NAME , LAST_NAME, GENDER , AGE, NATIONALITY FROM ALL_DATA 

CREATE TABLE DIM_DATE AS
SELECT DATE_SK , FULL_DATE , YEAR, MONTH , DAY FROM ALL_DATA 

CREATE TABLE DIM_AIRPORT AS
SELECT AIRPORT_SK , AIRPORT_NAME, ARRIVAL_AIRPORT,DEPARTURE_DATE, PILOT_NAME, FLIGHT_STATUS , AIRPORT_COUNTRY_CODE FROM ALL_DATA 

CREATE TABLE SUB_DIM_CONTINENT AS 
SELECT DISTINCT CONTINENTS, AIRPORT_CONTINENT,AIRPORT_COUNTRY_CODE, COUNTRY_NAME FROM ALL_DATA 

CREATE TABLE FACT_AIRLINE AS
SELECT AIRLINE_SK, PASSENGER_SK, DATE_SK, AIRPORT_SK FROM ALL_DATA

-- ADD CONSTRAINTS
--ADD PK

ALTER TABLE DIM_PASSENGER
ADD CONSTRAINT DIM_PASSENGER_PK PRIMARY KEY (PASSENGER_SK)

ALTER TABLE DIM_AIRPORT
ADD CONSTRAINT DIM_AIRPORT_PK PRIMARY KEY (AIRPORT_SK)

ALTER TABLE DIM_DATE
ADD CONSTRAINT DIM_DATE_PK PRIMARY KEY (DATE_SK)

ALTER TABLE FACT_AIRLINE
ADD CONSTRAINT FACT_AIRLINE_PK PRIMARY KEY (AIRLINE_SK)

ALTER TABLE SUB_DIM_CONTINENT
ADD CONSTRAINT SUB_DIM_CONTINENT_PK PRIMARY KEY (AIRPORT_COUNTRY_CODE)

SHOW PRIMARY KEYS

--ADD FOREIGN KEYS

ALTER TABLE FACT_AIRLINE
ADD CONSTRAINT FACT_DIM_PASSENGER_FK FOREIGN KEY (PASSENGER_SK) REFERENCES DIM_PASSENGER(PASSENGER_SK);

ALTER TABLE FACT_AIRLINE
ADD CONSTRAINT FACT_DIM_AIRPORT_FK FOREIGN KEY (AIRPORT_SK) REFERENCES DIM_AIRPORT(AIRPORT_SK); 

ALTER TABLE FACT_AIRLINE
ADD CONSTRAINT FACT_DIM_DATE_FK FOREIGN KEY (DATE_SK) REFERENCES DIM_DATE(DATE_SK);

ALTER TABLE DIM_AIRPORT
ADD CONSTRAINT DIM_AIRPORT_SUB_DIM_CONTINENT_FK FOREIGN KEY (AIRPORT_COUNTRY_CODE) REFERENCES SUB_DIM_CONTINENT(AIRPORT_COUNTRY_CODE);

SELECT * FROM DIM_AIRPORT
SELECT * FROM DIM_PASSENGER
SELECT * FROM DIM_DATE
SELECT * FROM SUB_DIM_CONTINENT
SELECT * FROM FACT_AIRLINE
