-- ADDING PK
ALTER TABLE DIM_PATIENT
ADD CONSTRAINT DIM_PATIENT_PK PRIMARY KEY (PATIENT_SK)

ALTER TABLE DIM_DIAGNOSIS
ADD CONSTRAINT DIM_DIAGNOSIS_PK PRIMARY KEY (DIAGNOSIS_SK)

ALTER TABLE DIM_DATE
ADD CONSTRAINT DIM_DATE_PK PRIMARY KEY (DATE_SK)

ALTER TABLE FACT_PATIENT_DIAGNOSIS
ADD CONSTRAINT FACT_PATIENT_DIAGNOSIS_PK PRIMARY KEY (PATIENT_DIAGNOSIS_SK)

--ADDING FOREIGN KEYS

ALTER TABLE FACT_PATIENT_DIAGNOSIS
ADD CONSTRAINT FACT_DIM_PATIENT_FK FOREIGN KEY (PATIENT_SK) REFERENCES DIM_PATIENT(PATIENT_SK);

ALTER TABLE FACT_PATIENT_DIAGNOSIS
ADD CONSTRAINT FACT_DIM_DIAGNOSIS_FK FOREIGN KEY (DIAGNOSIS_SK) REFERENCES DIM_DIAGNOSIS(DIAGNOSIS_SK); 

ALTER TABLE FACT_PATIENT_DIAGNOSIS
ADD CONSTRAINT FACT_DIM_DATE_FK FOREIGN KEY (DATE_SK) REFERENCES DIM_DATE(DATE_SK);

SELECT * FROM DIM_DATE
SELECT * FROM DIM_PATIENT
SELECT * FROM DIM_DIAGNOSIS
SELECT * FROM FACT_PATIENT_DIAGNOSIS
